### ISSUE TITLE
DNS utility functions

### ISSUE THREAD

**Issue by v0idpwn** [ocaml-multicore/eio#258]
Hi! First off, thanks for the amazing work in eio!

I'd like to have an API for `uv_getaddrinfo` and `uv_getnameinfo`. Luv has bindings to these on their DNS module: https://github.com/aantron/luv/blob/0ed668e87ca55d65f4f84422b0dd3381701c71b0/src/DNS.ml

If this feature is welcome in `eio`, I'd gladly send a PR.

**Comment by talex5** [comment]
Yes please! For uring, something like this could be used:

```ocaml
Eio_unix.run_in_systhread (fun () -> Unix.gethostbyaddr name)
```

There is a whole family of these `get*` functions in OCaml's `Unix` module. I'm not sure how many are useful. The types will need to be wrapped, because `Eio.Net` can't depend on `Unix` (it has to work on non-Unix platforms like MirageOS too).

**Comment by talex5** [comment]
OK, thanks for confirming!
