### ISSUE TITLE
`eio_main` selects `luv` by default on WSL

### ISSUE THREAD

**Issue by nojb** [ocaml-multicore/eio#304]
What the title says. I tried with `io-uring` by setting the `EIO_BACKEND` variable and it seems to work fine.

**Comment by talex5** [comment]
It's probably ignoring that if it thinks luv is the only available backend. What happens if you replace `Eio_main.run` with `Eio_linux.run`?

Perhaps `eio_linux` isn't even being built on WSL (it has `(enabled_if (= %{system} "linux"))` - not sure if that will be enabled or not).

https://github.com/ocaml-multicore/eio/issues/187 indicates uring didn't work on Windows, but things might have changed.

**Comment by nojb** [comment]
> It's probably ignoring that if it thinks luv is the only available backend. What happens if you replace `Eio_main.run` with `Eio_linux.run`?

It seems to work.

> Perhaps `eio_linux` isn't even being built on WSL (it has `(enabled_if (= %{system} "linux"))` - not sure if that will be enabled or not).

The variable `%{system}` is also `linux` under WSL.

> #187 indicates uring didn't work on Windows, but things might have changed.

Looking at the release notes of WSL https://docs.microsoft.com/en-us/windows/wsl/kernel-release-notes I spotted

![image](https://user-images.githubusercontent.com/113560/188310492-fabce9e4-d886-4699-84a3-d976cd952c77.png)

But #187 is from this year, so it should have been working by then...

**Comment by nojb** [comment]
See #306

**Comment by talex5** [comment]
> Yes, WSL is still on 5.10, but 5.15 should be released soon-ish (it is currently on "prerelease"), so I'm not sure it is worth the trouble to add a fallback
