### ISSUE TITLE
Undesirable wake-up semantics in `Stream.take`

### ISSUE THREAD

**Issue by iitalics** [ocaml-multicore/eio#356]
I'm still trying to figure out how to properly articulate this issue, but i believe the following semantics are undesirable:

```ocaml
open Eio

let main _env =
  let s1 = Stream.create 1 in
  let s2 = Stream.create 1 in
  let result =
    Switch.run @@ fun sw ->
    Fiber.fork ~sw (fun () -> Fiber.yield (); Stream.add s1 "A");
    Fiber.fork ~sw (fun () -> Fiber.yield (); Stream.add s2 "B");
    Fiber.first
      (fun () -> Stream.take s1)
      (fun () -> Stream.take s2)
  in
  traceln "result: %S" result;
  traceln "S1 length: %d" (Stream.length s1);
  traceln "S2 length: %d" (Stream.length s2)

let () = Eio_main.run main
```
output:
```
+result: "A"
+S1 length: 0
+S2 length: 0
```
despite `Stream.take s1` winning the `Fiber.first` race, and presumably cancelling `Stream.take s2`, both streams wind up empty. it would be preferable for cancellation to prevent `s2` from having its element removed, in other words should print:
```
+result: "A"
+S1 length: 0
+S2 length: 1
```
i believe this is because the implementation of stream takes a short cut where adding to an empty stream will pass the item immediately to the "waiter": https://github.com/ocaml-multicore/eio/blob/63f589669914b2531f44163dbf8256abdd3bc99a/lib_eio/stream.ml#L42-L44
this gives the reading fiber no ability to respond to a cancellation in time. a modified approach could be to have `readers` be `unit Waiters.t` such that this wake up is just a notification that there may be items in the queue, but the fiber still has to manually check the contents again. this check would be enqueued to the scheduler which means that there is an opportunity to cancel it.

im not sure if there is an argument to be made in favor of the current semantics, but to me this seems like there is serious potential to lose data when trying to use streams in conjunction with fiber cancellation

**Comment by talex5** [comment]
You might be interested in [Reagents](https://kcsrk.info/ocaml/multicore/2016/06/11/lock-free/), which allow these kinds of atomic patterns reliably (but are not currently integrated with Eio).

Without something like that, it can't work in the general case (multiple domains), because there is always a period of time after the first `Stream.take` has finished but before its fiber has exited, during which the other `Stream.take` could succeed.

I've found it's often easier to have a single stream with multiple writers for cases like this.
