### ISSUE TITLE
discuss: `perform GetActiveSwitch`

### ISSUE THREAD

**Issue by cdaringe** [ocaml-multicore/eio#364]
# problem

Counter to the [switch best practices](https://github.com/ocaml-multicore/eio#switches-1) section, periodically I need a fiber for some operation, and I want that fiber to explicitly operate within the context of the _current switch_.

For example, this week I wrote `let foo ~sw = Fiber.fork_daemon ~sw ...`, s.t. I would gracefully teardown the daemon when everything else cancelled in the current context. Thus, i ended up threading `~sw` through my stack.

it would have been lovely to to:

```ocaml
let foo _ = Fiber.fork_daemon ~sw:(perform GetActiveSwitch)` (* GetParentSwitch is probably better *)
```

and be on my merry way.

I could imagine that supporting such a feature may be _prohibitively_ expensive, but... i don't know the internals! Maybe it's not? :)

I'm not married to the feature/suggestion. Feel free to hastily close, just wanted to offer up the idea.

**Comment by talex5** [comment]
We don't want this by default because it defeats the purpose of having switches, which is knowing the lifetime of resources. e.g. if i do:

```ocaml
Eio_main.run @@ fun _ ->
foo ();
bar ()
```

then I know that any fibers or file-handles created by `foo` will have finished before `bar` runs, because I didn't pass a switch to `foo`.

Also, there isn't currently a concept of the "current switch" - sometimes there aren't any switches at all (as in the example above)!

However, if you have to do this (e.g. @patricoferris's example of an existing library that provides no way to pass it) you can store a switch in a fiber-local variable (`Eio.Fiber.with_binding`). But then for any code within that binding, you won't be able to tell easily when things are released.
