### ISSUE TITLE
Consider making the tests `.ml` instead of `.md`

### ISSUE THREAD

**Issue by sidkshatriya** [ocaml-multicore/eio#445]
I always find tests in any project a good source of documentation.

There are some really nice tests in the `tests` sub-folder but they are all in markdown format.

I request that these tests be converted to plain ml files using alcotest or similar. 

This will allow ocaml-lsp-server to understand these files so you can explore the code with goto definition etc.

**Comment by talex5** [comment]
You can copy-and-paste the code into e.g. `examples/hello/main.ml` if you want to explore them with LSP (though it would be nice to have LSP work with the .md files directly).

We're using MDX because it's way easier to have the test just return the result and have MDX format it and capture the output. For example, if you change something in Eio now then `dune runtest` will show a diff of all the resulting changes in the test output, and you can just decide whether to accept it or not. With Alcotest, you'd have to edit every test-case manually.

**Comment by sidkshatriya** [comment]
> For example, if you change something in Eio now then dune runtest will show a diff of all the resulting changes in the test output, and you can just decide whether to accept it or not.

Would https://github.com/janestreet/ppx_expect achieve the same objective?

**Comment by talex5** [comment]
ppx_expect has its own problems (including: you need to depend on it for all builds, not just testing; you need to define a bogus library to hold the tests; you have to write printers manually for the output; and it looks uglier).

But in any case, we can't use ppx_expect for the README, and it's more likely users will want to play with those examples than with the unit tests. So I'm much more interested in making MDX work better than in having two systems, each with their own problems.
