### ISSUE TITLE
Absolute path resolver?

### ISSUE THREAD

**Issue by patricoferris** [ocaml-multicore/eio#513]
I don't think it would be that uncommon for people to want to pass an `Eio.Fs.dir Eio.Path.t` into an `argv` for a process spawn. This happens  quite a lot in OBuilder (e.g. https://github.com/ocurrent/obuilder/blob/master/lib/btrfs_store.ml). At the moment I'm doing the `snd` trick which I know is wrong (I should probably follow the logic in the `resolve` method), it would be nice to have:

```ocaml
val resolve_absolute : Eio.Fs.dir Eio.Path.t -> string
```

**Comment by talex5** [comment]
It would have to return an option, as some paths aren't in the default namespace.

With the Linux backend sandboxed directories are represented as an FD and it's not clear how to turn that into a string. And the POSIX backend is likely to do the same thing in the future. I guess we could remember the path when it was created and hope it hasn't changed.

An initial version that returns None for sandboxed directories would be fine though.

A more general API would be to ask for a path relative to another one, so that `resolve_absolute path` becomes `relative_path ~base:fs path`, but it's not obvious how to do that, except by listing each parent directory in turn, looking for a matching inode.

**Comment by avsm** [comment]
While I agree with Patrick's usecase (passing a Path into a process spawn), I don't think that reconstructing a filesystem path from an fd is a good direction to go in.  It's just not portable.  Better to somehow propagate the original names used to open the fd around instead.

**Comment by talex5** [comment]
I'll probably add an `Eio_unix.native_path.opt : _ Path.t -> string option` for this. But probably best to wait for #553 to go in first, as otherwise it will conflict with that.

**Comment by NickHu** [comment]
As far as I can tell, this is not fixed as #603 does not provide any way to map a relative path to an absolute one (when possible).

**Comment by talex5** [comment]
The title of this issue doesn't quite match the description. Passing a path to spawn requires a native path, but it doesn't have to be absolute (it can be relative to the cwd).

Turning a relative path into an absolute one can also be useful. Calling `Unix.realpath` on the native path might be a reasonable work-around though.

**Comment by avsm** [comment]
@talex5 wrote:
> With the Linux backend sandboxed directories are represented as an FD and it's not clear how to turn that into a string

Since it's Linux-specific, would readlink on `/proc/self/fd/<num>` work with directories as it does for files?

**Comment by talex5** [comment]
Using /proc on Linux does seem to work (however, it also resolves symlinks, which is typically not part of getting absolute path). Note that `eio_posix` now also uses FDs for directories.
